CREATE TABLE AALLKP
(
  OPERATION_CODE   VARCHAR2(1 BYTE),
  EFFECTIVE_DATE   NUMBER(15),
  EXPIRATION_DATE  NUMBER(15),
  LEVEL_0          VARCHAR2(15 BYTE),
  LEVEL_1          VARCHAR2(5 BYTE),
  LEVEL_2          VARCHAR2(5 BYTE),
  LIKE_LEVEL_0     VARCHAR2(15 BYTE),
  LIKE_LEVEL_1     VARCHAR2(5 BYTE),
  LIKE_LEVEL_2     VARCHAR2(5 BYTE),
  USE_FOR_OH       VARCHAR2(1 BYTE)
)
TABLESPACE AAMDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;