CREATE TABLE AAM.AALMOD
(
  OPERATION_CODE   VARCHAR2(1 BYTE),
  MODEL_NAME       VARCHAR2(80 BYTE),
  LEVEL_1          VARCHAR2(50 BYTE),
  LEVEL_2          VARCHAR2(50 BYTE),
  LEVEL_3          VARCHAR2(50 BYTE),
  LEVEL_4          VARCHAR2(50 BYTE),
  LEVEL_5          VARCHAR2(50 BYTE),
  LOCATION_NUMBER  NUMBER(15),
  THRESHOLD        NUMBER(15,4),
  TARGET           NUMBER(15,4),
  SIZE_RATIO       NUMBER(15,4),
  MINIMUM          NUMBER(15),
  MAXIMUM          NUMBER(15),
  EXPIRATION_DATE  NUMBER(15),
  VIEW_ID          NUMBER(15)
)
TABLESPACE AAMDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
