CREATE PUBLIC DATABASE LINK "EKB_FMK"
CONNECT TO "FMK" IDENTIFIED BY kmf02252004
USING '(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = u060jdad202.kroger.com)(PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = jdadekb) (SERVER = DEDICATED)))';