select *
  from dba_directories
  ;
  
SELECT * FROM dba_tab_privs WHERE table_name='ALC_LOG';
  
GRANT READ, WRITE ON DIRECTORY SYS.ALC_LOG TO AAM WITH GRANT OPTION; 
GRANT READ, WRITE ON DIRECTORY SYS.ALC_LOG TO AAMFM WITH GRANT OPTION; 