SELECT  *
  FROM  accp.TSA_TEMP_STORAGE
 WHERE  USER_ID = 'APDT-RM'
   and  APPL_ID = 'PRMZ000D'
   --AND  SUBSTR(REC_KEY,1,7) = :WS-SCHD-JUL-X
  WITH  UR;

SELECT  *
FROM  accp.TSA_TEMP_STORAGE
WHERE  USER_ID = 'APHD'
  and  APPL_ID = 'RM'
WITH  UR;
