SELECT LO1.LOC_ID
      ,LO1.LOC_NBR
      ,PT1.PARM_TXT
  FROM ACCP.PT1_PARM_TBL PT1
      ,ACCP.LO1_LOC      LO1
      ,ACCP.LO2_LOC_TM   LO2
 WHERE PT1.PARM_GRP_NAM_TX       = 'SAC'
   AND PT1.PARM_ID               = 'MASTER PARM'
   AND PT1.CMNT_ID              != '*'
   AND SUBSTR(PT1.PARM_TXT,23,1) = '-'
   AND SUBSTR(PT1.PARM_TXT,5,5)  = LO1.LOC_ID
   AND LO1.RPLN_SRCE_FLG         = 'Y'
   AND LO2.LOC_ID                = LO1.LOC_ID
   AND CURRENT TIME + (LO1.TM_ZONE_FCTR * 60) MINUTES < LO2.BUS_CLS_TM
   AND CURRENT TIME + (LO1.TM_ZONE_FCTR * 60) MINUTES < '21:00:00'
;

WITH DATE AS (
  SELECT CURRENT DATE AS DATE
    FROM ACCP.TT1_TRUTH_TBL
), NOVEMBER AS (
  SELECT DATE - (DAY(DATE)-1) DAYS AS FIRST_OF_MONTH
    FROM DATE
), DOW AS (
  SELECT DAYOFWEEK(FIRST_OF_MONTH) AS VAL
    FROM NOVEMBER
)
SELECT CASE WHEN VAL <= 5 THEN
         27 - VAL
       ELSE
         34 - VAL
       END AS THANKSGIVING
  FROM DOW
;