SELECT *
  FROM ACCP.PT1_PARM_TBL
 WHERE PARM_GRP_NAM_TX = 'PSAC010D'
   AND PARM_ID         = 'SAC010'
 order by rec_alt_ts desc
 ;

UPDATE ACCP.PT1_PARM_TBL
   SET PARM_TXT = '00025 201713272018-01-13181E NNYNNNNN CCY SAC150  2018-01-13'
 WHERE PARM_GRP_NAM_TX = 'PSAC010D'
   AND PARM_ID         = 'SAC010'
   AND SEQ_NBR         = 6
   ; 

WITH TRUTH AS (
  SELECT 1 AS A FROM ACCP.TT1_TRUTH_TBL
), EMAIL AS (
  SELECT TRIM(PARM_TXT)                        AS ADDR
   FROM ACCP.PT1_PARM_TBL
  WHERE PARM_GRP_NAM_TX       = 'PSAC016D'
    AND PARM_ID               = 'EMAIL'
), PARM AS (
  SELECT SUBSTR(PARM_TXT,1,5)                  AS LOC
        ,SUBSTR(PARM_TXT,15,10)                AS DT
        ,SUBSTR(PARM_TXT,25,4)                 AS DTCODE
        ,SUBSTR(PARM_TXT,39,3)                 AS FLAGS
        ,SUBSTR(PARM_TXT,43,8)                 AS PGMNM
        ,CAST(SUBSTR(PARM_TXT,51,10) AS DATE)  AS UPDDT
   FROM ACCP.PT1_PARM_TBL
  WHERE PARM_GRP_NAM_TX       = 'PSAC010D'
    AND PARM_ID               = 'SAC010'
    AND CMNT_ID              != '*'
), LOAD_TODAY AS (
  SELECT *
    FROM PARM
   WHERE FLAGS = 'CYY'
   ORDER BY LOC, DT
), LOAD_TOMORROW AS (
  SELECT *
    FROM PARM
   WHERE FLAGS = 'PYY'
   ORDER BY LOC, DT
), LOAD_NEXTWEEK AS (
  SELECT *
    FROM PARM
   WHERE FLAGS = 'YYY'
   ORDER BY LOC, DT
), EXEMPT_REMOVED AS (
  SELECT *
    FROM PARM
   WHERE DT = CURRENT DATE
     AND PGMNM = 'SAC150'
   ORDER BY LOC, DT
), MESSAGES AS (
  SELECT SUBSTR(PARM_TXT,1,5)                  AS LOC
        ,SUBSTR(PARM_TXT,7,10)                 AS DT
        ,SUBSTR(PARM_TXT,18,43)                AS MSG
   FROM ACCP.PT1_PARM_TBL
  WHERE PARM_GRP_NAM_TX       = 'PSAC016D'
    AND PARM_ID               = 'SAC016'
    AND CMNT_ID              != '*'
  UNION 
 SELECT LOC
       ,DT
       ,CAST(
        CASE FLAGS
        WHEN 'CCC' THEN
          'SALES RELOADED IN WB AND PUSHED TO SS '||
          'YESTERDAY'
        WHEN 'YNN' THEN
          'SALES WILL BE DROPPED NEXT WEEK - NO '||
          'RELOAD NEEDED'
        WHEN 'PNN' THEN
          'SALES WILL BE DROPPED TONIGHT - NO '||
          'RELOAD NEEDED'
        END AS CHAR(50)) AS MSG
   FROM PARM
  WHERE FLAGS IN ('CCC','YNN','PNN')
  ORDER BY LOC, DT
), COUNTS AS (
  SELECT (SELECT COUNT(*) FROM LOAD_TODAY)     AS CNT1
        ,(SELECT COUNT(*) FROM LOAD_TOMORROW)  AS CNT2
        ,(SELECT COUNT(*) FROM LOAD_NEXTWEEK)  AS CNT3
        ,(SELECT COUNT(*) FROM EXEMPT_REMOVED) AS CNT4
        ,(SELECT COUNT(*) FROM MESSAGES)       AS CNT5
    FROM TRUTH
), RPT AS (
  SELECT 1 AS SORT
        ,CAST('HELO MVSHOST' AS CHAR(80)) AS D
    FROM TRUTH
   UNION
  SELECT 2 AS SORT
        ,CAST('MAIL FROM: <PSAC016D@corp.e300.kroger.com>'
         AS CHAR(80)) AS D
    FROM TRUTH
   UNION
  SELECT 3 AS SORT
        ,CAST('RCPT TO: <'||EMAIL.ADDR||'>' AS CHAR(80)) 
         AS D
    FROM EMAIL
   UNION
  SELECT 4 AS SORT
        ,CAST('DATA' AS CHAR(80)) AS D
    FROM TRUTH
   UNION
  SELECT 5 AS SORT
        ,CAST('SUBJECT: SDC STATUS UPDATE - PSAC016D'
         AS CHAR(80)) AS D
    FROM TRUTH
   UNION
  SELECT 6 AS SORT
        ,CAST(SPACE(80) AS CHAR(80)) AS D
    FROM TRUTH
   UNION
  SELECT 7 AS SORT
        ,CAST('STORES THAT NEED SALES LOADED TODAY:'
         AS CHAR(80)) AS D 
    FROM TRUTH, COUNTS
   WHERE CNT1 > 0
   UNION
  SELECT 8 AS SORT
        ,CAST(LOC||' -> '||DT||' ('||DTCODE||')' 
         AS CHAR(80))AS D 
    FROM LOAD_TODAY, COUNTS
   WHERE CNT1 > 0
   UNION
  SELECT 9 AS SORT
        ,CAST(SPACE(80) AS CHAR(80))AS D 
    FROM TRUTH, COUNTS
   WHERE CNT1 > 0
   UNION
  SELECT 10 AS SORT
        ,CAST('STORES THAT WILL NEED SALES LOADED '||
        'TOMORROW:' AS CHAR(80)) AS D 
    FROM TRUTH, COUNTS
   WHERE CNT2 > 0
   UNION
  SELECT 11 AS SORT
        ,CAST(LOC||' -> '||DT||' ('||DTCODE||')' 
         AS CHAR(80))AS D 
    FROM LOAD_TOMORROW, COUNTS
   WHERE CNT2 > 0
   UNION
  SELECT 12 AS SORT
        ,CAST(SPACE(80) AS CHAR(80))AS D 
    FROM TRUTH, COUNTS
   WHERE CNT2 > 0
   UNION
  SELECT 13 AS SORT
        ,CAST('STORES THAT WILL NEED SALES LOADED '||
        'NEXT WEEK:' AS CHAR(80)) AS D 
    FROM TRUTH, COUNTS
   WHERE CNT3 > 0
   UNION
  SELECT 14 AS SORT
        ,CAST(LOC||' -> '||DT||' ('||DTCODE||')' 
         AS CHAR(80))AS D 
    FROM LOAD_NEXTWEEK, COUNTS
   WHERE CNT3 > 0
   UNION
  SELECT 15 AS SORT
        ,CAST(SPACE(80) AS CHAR(80))AS D 
    FROM TRUTH, COUNTS
   WHERE CNT3 > 0
   UNION
  SELECT 16 AS SORT
        ,CAST('STORES TAKEN OFF OF EXEMPT TODAY'||
        '(PSAC150D):' AS CHAR(80)) AS D 
    FROM TRUTH, COUNTS
   WHERE CNT4 > 0
  UNION
  SELECT 17 AS SORT
        ,CAST(LOC AS CHAR(80)) AS D 
    FROM EXEMPT_REMOVED, COUNTS
   WHERE CNT4 > 0
   UNION
  SELECT 18 AS SORT
        ,CAST(SPACE(80) AS CHAR(80))AS D 
    FROM TRUTH, COUNTS
   WHERE CNT4 > 0
   UNION
  SELECT 19 AS SORT
        ,CAST('MISCELLANEOUS MESSAGES:' 
         AS CHAR(80)) AS D 
    FROM TRUTH, COUNTS
   WHERE CNT5 > 0
  UNION
  SELECT 20 AS SORT
        ,CAST(LOC||' '||DT||' '||MSG 
         AS CHAR(80)) AS D 
    FROM MESSAGES, COUNTS
   WHERE CNT5 > 0
   UNION
  SELECT 98 AS SORT
        ,CAST('NO DATA TODAY' AS CHAR(80)) 
         AS D
    FROM COUNTS
   WHERE CNT1=0 AND CNT2=0 AND CNT3=0 AND CNT4=0 
     AND CNT5=0
   UNION
  SELECT 99 AS SORT
        ,CAST('.' AS CHAR(80)) AS D
    FROM TRUTH
)
SELECT D
  FROM RPT
 ORDER BY SORT, D
  WITH UR
;
  
 