  SELECT DIOBLI, DIOBNM, DIOBTP, DIOBAT, DIOBSZ
    FROM QUSRSYS.QAEZDISK 
  WHERE DIOBLI > ''
ORDER BY DIOBSZ DESC
  FETCH FIRST 10 ROWS ONLY
;
--TO FIND OUT WHICH LIBRARIES ARE TAKING UP THE MOST SPACE ON THE
--SYSTEM, RUN THE COMMAND  SBMJOB CMD(RTVDSKINF) JOB(RTVDSKINF), THEN
--RUN THE ABOVE SQL.


