  SELECT DIOBLI, SUM(DIOBSZ) AS TOT 
    FROM QUSRSYS.QAEZDISK 
GROUP BY DIOBLI
ORDER BY TOT DESC

--TO FIND OUT WHICH LIBRARIES ARE TAKING UP THE MOST SPACE ON THE
--SYSTEM, RUN THE COMMAND  SBMJOB CMD(RTVDSKINF) JOB(RTVDSKINF), THEN
--RUN THE ABOVE SQL.


